DROP TABLE BILETY IF EXISTS;
DROP TABLE LOTY IF EXISTS;
DROP TABLE KLIENCI IF EXISTS;

CREATE TABLE LOTY
(
ID_LOTU INTEGER PRIMARY KEY,
SKAD VARCHAR NOT NULL,
DOKAD VARCHAR NOT NULL,
DATA_WYLOTU DATE,
CENA INTEGER,
MIEJSCA_BIZNES INTEGER,
MIEJSCA_EKONO INTEGER
);


CREATE TABLE KLIENCI
(
ID_KLIENTA INTEGER PRIMARY KEY,
IMIE VARCHAR NOT NULL,
NAZWISKO VARCHAR NOT NULL,
ADRES VARCHAR,
DATA_URODZENIA DATE,
TELEFON VARCHAR
);

CREATE TABLE BILETY 
(
ID_BILETU INTEGER NOT NULL PRIMARY KEY,
RODZAJ_ZNIZKI VARCHAR,
STANDARD_LOTU VARCHAR,
DATA_ZAKUPU DATE,
ZAPLACONA_CENA INTEGER,
FK_ID_KLIENTA INTEGER,
FK_ID_LOTU INTEGER 
);


ALTER TABLE BILETY ADD FOREIGN KEY (FK_ID_KLIENTA)
REFERENCES KLIENCI (ID_KLIENTA);

ALTER TABLE BILETY ADD FOREIGN KEY (FK_ID_LOTU)
REFERENCES LOTY (ID_LOTU);

INSERT INTO LOTY VALUES(1, 'Londyn', 'Nowy Jork', '2010-12-11', 2500, 20, 120);
INSERT INTO LOTY VALUES(2, 'Londyn', 'Nowy Jork', '2010-10-11', 3000, 20, 120);
INSERT INTO LOTY VALUES(3, 'Londyn', 'Nowy Jork', '2010-09-10', 3000, 20, 120);
INSERT INTO LOTY VALUES(4, 'Londyn', 'Nowy Jork', '2010-12-21', 2500, 20, 120);
INSERT INTO LOTY VALUES(5, 'Londyn', 'Nowy Jork', '2011-01-01', 2500, 20, 120);
INSERT INTO LOTY VALUES(6, 'Londyn', 'Nowy Jork', '2011-02-03', 2400, 20, 120);
INSERT INTO LOTY VALUES(7, 'Londyn', 'Nowy Jork', '2011-04-01', 2300, 20, 120);
INSERT INTO LOTY VALUES(8, 'Londyn', 'Nowy Jork', '2011-05-02', 2200, 20, 120);

